### PR TITLE
Prepare repository for transfer to @in-toto

### PR DESCRIPTION
**Pull request by adityasaky**
Renames the go module and emphasizes that this is a prototype.

https://github.com/in-toto/community/issues/14

### CODE REVIEW

**Comment by adityasaky** [comment]
Once this is merged, I think we can ask for a repository transfer to @in-toto.

cc @santiagotorres

**Review by trishankatdatadog — CHANGES_REQUESTED** [review]
Please add 2-3 maintainers (including myself), and we're good to go

**Comment by adityasaky** [comment]
Sounds good. I've already added @marcelamelara, I'll add you as well.

**Comment by adityasaky** [comment]
@trishankatdatadog could you accept the invite? https://github.com/adityasaky/in-toto-attestation-verifier/invitations

**Review by marcelamelara — APPROVED** [review]
LGTM thanks!

**Review by trishankatdatadog — APPROVED** [review]
Done, LGTM, let's go 🚀

**Pull request merged**
